// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    Board: typeof import('./src/components/Board.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
  }
}

export {}
